services:
  php:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Loja
      MYSQL_USER: arthur
      MYSQL_PASSWORD: 1234
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge